### ISSUE TITLE
SiEPIC_Keybindings.lym

### ISSUE THREAD

**Issue by lukasc-ubc** [lukasc-ubc/SiEPIC-Tools#1]
Syntax error.  Hence the SiEPIC configure shortcut keys menu item isn't appearing.

![image](https://user-images.githubusercontent.com/15843200/33929202-7758cfea-df9d-11e7-86cf-2b4517e65d09.png)

**Comment by bpoulse** [comment]
Even when run explicitly it does not add a menu binding. I attempted to create a new lym macro in the local folder with the same effect. Might be a bug in 0.25.
