### ISSUE TITLE
Lumerical: Launch Lumerical

### ISSUE THREAD

**Issue by bpoulse** [lukasc-ubc/SiEPIC-Tools#17]
Implement function for launching lumerical

**Comment by lukasc-ubc** [comment]
Implemented. Works on EBeam.  Using old integration method (system call).  

Now working on Python integration.

**Comment by lukasc-ubc** [comment]
Python integration working on OSX.  To do for Windows / Linux.

**Comment by lukasc-ubc** [comment]
implemented.
