### ISSUE TITLE
Windows GUI font scaling issue

### ISSUE THREAD

**Issue by lukasc-ubc** [lukasc-ubc/SiEPIC-Tools#25]
On Windows, when I change the display configuration "change the size of all items", e.g., 200%, the GUI for Waveguides gets messed up.

All the other KLayout GUIs are fine.

![image](https://user-images.githubusercontent.com/15843200/34067586-b8663f70-e1de-11e7-8742-e33250e01629.png)

**Comment by bpoulse** [comment]
I tried a fix for the gui, can you let me know what the result on that VM is?

**Comment by lukasc-ubc** [comment]
![image](https://user-images.githubusercontent.com/15843200/34076580-7e2e0c3a-e2a0-11e7-84fb-901ef88a660b.png)

**Comment by bpoulse** [comment]
@lukasc-ubc can you once again let me know if the changes I made make any difference at all? It works with changing my monitor resolution but not sure if that is the issue.

**Comment by lukasc-ubc** [comment]
Looks great on OSX:
![image](https://user-images.githubusercontent.com/15843200/34315524-b622ec0c-e735-11e7-8d49-0959912fde72.png)

**Comment by lukasc-ubc** [comment]
Here is what it looks like on Windows (7 rr 8) with scaling set to 150%:

![image](https://user-images.githubusercontent.com/15843200/34315577-76416aea-e736-11e7-98c8-e60734e3339b.png)

**Comment by lukasc-ubc** [comment]
Is there any way to make the stretch thing on the bottom right corner enabled, so that we can stretch the window if necessary?

**Comment by bpoulse** [comment]
It should be enabled already. I will tinker around some more.
