### ISSUE TITLE
Hot keys

### ISSUE THREAD

**Issue by lukasc-ubc** [lukasc-ubc/SiEPIC-Tools#27]
I don't what changed.  But yesterday the hotkeys were working, and were automatically loaded.

Sometime tonight they stopped.  Have to run manually "SiEPIC installation and initalization", each time a new layout is created or a new GDS file is loaded.

**Comment by lukasc-ubc** [comment]
Actually, I checked the version before I made the edits tonight, and it seems like this was also an issue before too...

**Comment by bpoulse** [comment]
There seem to be several issues with 0.25 involving this. For myself, the hotkeys work with no issue on Windows 10. However, your addition of the 'SiEPIC.lym' to the menu does not show up (as mentioned before) regardless of if it is in the salt folder or local.

**Comment by lukasc-ubc** [comment]
Could you post something on KLayout GitHub?

I believe the old PDK works though right?


Lukas Chrostowski
Professor, ECE
University of British Columbia
604-822-8507
http://www.mina.ubc.ca/lukasc
http://siepic.ubc.ca

**Comment by lukasc-ubc** [comment]
The following method works:

https://github.com/lukasc-ubc/SiEPIC-Tools/commit/6dd23ee5d9185c2811d762df2c1b06a9d65062a2

**Comment by bpoulse** [comment]
Added shortcuts to config-keybindings, solves issue.

**Comment by lukasc-ubc** [comment]
This solution for some reason doesn't work on 0.24 (OSX, Python2).  Menus don't have the hotkeys.  I recall struggling with this as well, and concluded that the way to do it was using the pymacros and the config GUI.

**Comment by bpoulse** [comment]
Alright, no sense wasting more time. I'll change it back to pymacros.

**Comment by lukasc-ubc** [comment]
weird.  In settings the key bindings are correct, yet the menus are missing them.But when I push OK (with making any changes), then the menu gets updated correctly.  Perhaps there just needs to be a refresh command issued?

**Comment by bpoulse** [comment]
Yeah, its something to do with the referencing we cant control very well. I've trying a ton of different things to try and get actions working but they seem very finicky. I am making pymacros for the menu items now

**Comment by lukasc-ubc** [comment]
Ok, thanks!
I’ve found a few other bugs that I’ve fixed, for the path-waveguide functions.  
working on component snapping now.  I notice that your naming suggests that the action is different from what I originally had.

Previous “Shift-O”.  Select object you wish to move, then hover mouse to where you want it to go…

Yours: simpler - go to the nearest pin.

You think the simpler one is better / sufficient?  Did you find problems with the way I did it before?

thanks

**Comment by bpoulse** [comment]
I didn't intend for it to be functionally different. I liked the way it was previously, had no issues. I havent done anything for component snapping, the function is defined in scripts.py but not implemented. The other snapping is implemented in extend.py for Paths, which just finds the nearest pin available (with correct rotation).

**Comment by lukasc-ubc** [comment]
good.  I'll implement the same thing then...

**Comment by bpoulse** [comment]
Changed to pymacros. If you don't mind verifying on your version then we can close.

**Comment by lukasc-ubc** [comment]
Windows 7:

 - W, Shift-W, etc are working.
 - missing the "SiEPIC initialize" menu at the beginning.
 - you introduced a new error where the Waveguide (W) function doesn't work when trying to connect to a component.  (maybe I fixed something which you over-wrote in this commit?)

![image](https://user-images.githubusercontent.com/15843200/34076985-721e1196-e2ab-11e7-8552-e70ec8882037.png)

![image](https://user-images.githubusercontent.com/15843200/34076993-a64025e0-e2ab-11e7-9274-dbac8b016907.png)

![image](https://user-images.githubusercontent.com/15843200/34076995-b4ee44a0-e2ab-11e7-99d1-f070d143d9bf.png)

**Comment by lukasc-ubc** [comment]
On OSX, version 0.24.10

 - SiEPIC Init menu is there...
 - same issue as Windows (W)
 - Shift-W has yet another error

![image](https://user-images.githubusercontent.com/15843200/34076999-003fd34c-e2ac-11e7-86a2-3b7402d9a63a.png)

![image](https://user-images.githubusercontent.com/15843200/34077002-0b0021d8-e2ac-11e7-87e1-4f62fb3c0971.png)

![image](https://user-images.githubusercontent.com/15843200/34077006-31a6af3c-e2ac-11e7-9f5e-a325354d8b4e.png)

**Comment by lukasc-ubc** [comment]
I think the issue is with the following that you added in your last commit:

![image](https://user-images.githubusercontent.com/15843200/34077017-8ae05d14-e2ac-11e7-9d66-7e6f8900aed6.png)

**Comment by bpoulse** [comment]
Ah. I accidentally pushed untested changes to the map with it. I will fix it.

**Comment by bpoulse** [comment]
@lukasc-ubc with removing that code and the other fixes you did is this closed?
