### ISSUE TITLE
Change waveguide hotkey

### ISSUE THREAD

**Issue by bpoulse** [lukasc-ubc/SiEPIC-Tools#3]
Waveguide hotkey should not show GUI, instead use 'current configuration'

This means GUI parameters must be initialized BEFORE gui.show()

**Comment by lukasc-ubc** [comment]
Perhaps show the GUI the first time only.  You can use the same approach as what I did in v0.1.x, namely I add a layout property and check if it is defined.  (problem is that GDS doesn't save this variable, so you need to make the choice each time)...

**Comment by lukasc-ubc** [comment]
Thanks Brett!  I like the way you implemented it.
