### ISSUE TITLE
Waveguide changes

### ISSUE THREAD

**Issue by bpoulse** [lukasc-ubc/SiEPIC-Tools#31]
- Change LayerInfo list to actual names
- Change offset/slot to subtraction
- Guiding shape fix
- Waveguide to path should read path width from PCell

**Comment by lukasc-ubc** [comment]
I fixed 
 - Waveguide to path should read path width from PCell

the others to do.

**Comment by lukasc-ubc** [comment]
Guiding shape. Looks like you've improved it, but there is a problem (perhaps not important).  When you instantiate a Waveguide PCell, then Partial select stretch it, the PCell doesn't update.

Interestingly, the one created by "W" works fine.

This is on 0.24.10.  Might be different on 0.25.

**Comment by bpoulse** [comment]
Interesting. I'll investigate.

**Comment by lukasc-ubc** [comment]
it's funny, each time we fix something, something else breaks (particularly with the new features in 0.25, which aren't there in 0.24).  hopefully my fixes of your fixes didn't add more problems.

**Comment by nedanr** [comment]
![error](https://user-images.githubusercontent.com/35555287/35947972-4ed032f8-0c38-11e8-91e8-7979688b797c.png)

**Comment by mustafacc** [comment]
Hi nedanr, This issue is SiEPIC_IME PDK specific, it has been fixed on the master repository but not yet released on kLayout packages.

**Comment by lukasc-ubc** [comment]
I just released the latest versions of SiEPIC-Tools, SiEPIC_IME_Library, and SiEPIC_EBeam_PDK for the Package Manager, which fixes this issue.
