### ISSUE TITLE
Error in get_technology_by_name()

### ISSUE THREAD

**Issue by mustafacc** [lukasc-ubc/SiEPIC-Tools#33]
https://github.com/lukasc-ubc/SiEPIC-Tools/blob/master/klayout_dot_config/python/SiEPIC/utils.py#L29

When called, i.e. in https://github.com/lukasc-ubc/SiEPIC_EBeam_PDK/blob/v0.3.0/klayout_dot_config/tech/EBeam/pymacros/SiEPIC_EBeam%20Library.lym#L127

The following error pops up
![capture](https://user-images.githubusercontent.com/8067688/34296272-4c96295c-e72b-11e7-9ce0-f755ff6fb7f9.PNG)

This error also occurs when called for any other technology

**Comment by lukasc-ubc** [comment]
Fixed in net-dev, and merged to master.
