### ISSUE TITLE
Cell Hierarchy Issue?

### ISSUE THREAD

**Issue by bpoulse** [lukasc-ubc/SiEPIC-Tools#43]
@lukasc-ubc @jaspreetj @mustafacc 

Has anyone noticed an issue with PCells in KLayout 0.25 like below?

![image](https://user-images.githubusercontent.com/3443338/34581100-42bbc25c-f15d-11e7-81b9-fd142f9b6f5e.png)

When inserting a new PCell, the instance does not show up in the hierarchy where it has been placed. In this example, I tried to add a Lumerical Laser to the cell v1.

**Comment by lukasc-ubc** [comment]
Right-click in the white space in the cells, and turn on hierarchy?

**Comment by bpoulse** [comment]
Yes, you are right, I didn't realize it was a setting. Flat cell list was enabled.
