### ISSUE TITLE
Missing module "load_lumapi": Setup Lumerical INTERCONNECT Compact Model Library

### ISSUE THREAD

**Issue by mustafacc** [lukasc-ubc/SiEPIC-Tools#52]
When attempting to setup INTC CML (for any package) in kLayout, I see the following:
![capture](https://user-images.githubusercontent.com/8067688/35138775-f1aeffca-fca4-11e7-94ce-6bfb9b1e5459.PNG)

**Comment by lukasc-ubc** [comment]
I checked using a windows VM and was not able to get this error.  Using SiEPIC-Tools v0.3.10.

**Comment by lukasc-ubc** [comment]
one line fix in interconnect.py line 32:
     from . import load_lumapi
