### ISSUE TITLE
Can add a feature of "resize waveguide" for SiEPIC Tools? Thanks1

### ISSUE THREAD

**Issue by zhongjinlin** [lukasc-ubc/SiEPIC-Tools#58]

**Comment by lukasc-ubc** [comment]
Jaspreet - could you please add your script?  Thanks!

**Comment by jaspreetj** [comment]
I apologize for my lateness. I have been working on fixing CMLs, I will add it by this weekend.

**Comment by lukasc-ubc** [comment]
@zhongjinlin: Jaspreet added this.  It is now in SiEPIC | Waveguides | Resize

Thank you, @jaspreetj!

**Comment by zhongjinlin** [comment]
Thanks!
