### ISSUE TITLE
Problem installing siepic addon

### ISSUE THREAD

**Issue by gabrilator91** [lukasc-ubc/SiEPIC-Tools#69]
Hi, 

I am part of the EdX course, and I was trying to add the siepic pdk extension into klayout. 

I'm getting the following error
"Stream has unknown format", after being asked If I allowed the macros to be executed. 

After that, I can see the SiEPIC addon, but when I try to add the elements to my project, the SiEPIC library is empty. 

I use a windows machine, 64 bits and was trying to install the 0.25 version. 

Could someone please give me a hand :) ? 
Thanks!
Gabriel

**Comment by mustafacc** [comment]
Hi Gabriel,

Can you please ensure you are following those steps:

http://recordit.co/fK7AsDud0v

Make sure you click on the "T" icon above EBeam

**Comment by lukasc-ubc** [comment]
https://github.com/lukasc-ubc/SiEPIC-Tools/wiki/Common-problems

**Comment by lukasc-ubc** [comment]
Also please install 0.25.1 (the latest)

**Comment by gabrilator91** [comment]
Thank you! It's fine now 😊

________________________________
De: Lukas Chrostowski <notifications@github.com>
Enviado: lunes, 26 de febrero de 2018 1:12:00
Para: lukasc-ubc/SiEPIC-Tools
Cc: Gabriel Cebria Oliveira; Author
Asunto: Re: [lukasc-ubc/SiEPIC-Tools] Problem installing siepic addon (#69)


Also please install 0.25.1 (the latest)
