### ISSUE TITLE
Warning for developers (pip.main ceased to exist after pip 10.0)

### ISSUE THREAD

**Issue by thomaslima** [lukasc-ubc/SiEPIC-Tools#86]
Hello, I am testing the new klayout version 0.25.3 with python3 from brew. It will be soon in matthias's website, but I noticed a few errors with the siepic packages. Notably we cannot use pip.main anymore to install anything.

Read this.
https://pip.pypa.io/en/latest/user_guide/#using-pip-from-your-program

**Comment by thomaslima** [comment]
my workaround was to call the new main function in pip._internal. The main issue they raised for the change is that it usually quits the python interpreter with a system exit exception, so not advisable to use as a module. So they advise to call it as a subprocess. that means that if there is a bug in the installer scripts, klayout's python interpreter will crash, and i think klayout throws an error and crashes with it. so we have to be a bit conservative with installing packages for those who don't have pip in their klayout.

**Comment by lukasc-ubc** [comment]
I added MessageBox GUIs in all the places where pip install tries to do its thing.  

I notice that your Mac OS build keeps the pip install modules local to KLayout, rather than system wide.  So reinstalling KLayout requires a fresh pip install of numpy, etc.

**Comment by thomaslima** [comment]
I'm closing since you've merged the PR.
